### ISSUE TITLE
Impossible to read address bar in Nightly 76

### ISSUE THREAD

**Issue by lukaszgo1** [javidominguez/MozillaScripts#7]
In Nightly 76 it is no longer possible to access security info  like in previous version, so script_URL fails.
It looks like that routing mouse to the "View site information" displays it in a tooltip if the connection is using https, so this might work.
Alternatively if security info is not so important address of the current page is exposed as a IAccessible accValue on the root document.

**Comment by tage64** [comment]
This is still not possible with stable 76.0.

**Comment by javidominguez** [comment]
I've fixed it. URL is now read but security information is no longer accessible.
